### PR TITLE
Remove internal entries from stack trace

### LINKED ISSUE #163: Hide internal stack traces
Given the following tests
```ts
import { expect } from "earljs"

describe('example', () => {
  it('regular failure', () => {
    expect(123).toEqual(456)
  })

  it('async failure', async () => {
    async function foo() {
       throw new Error('bar')
    }
    await expect(foo()).toBeRejected('baz')
  })
})
```

The output is:
```

  1) example
       regular failure:

      AssertionError: 123 not equal to 456
Hint: value mismatch
      + expected - actual

      -123
      +456
      
      at Control.assert (/home/piotr/Documents/projects/l2beat/node_modules/earljs/dist/Control.js:14:23)
      at toEqual (/home/piotr/Documents/projects/l2beat/node_modules/earljs/dist/validators/toEqual.js:11:17)
      at Expectation.toEqual (/home/piotr/Documents/projects/l2beat/node_modules/earljs/dist/Expectation.js:48:31)
      at Context.<anonymous> (test/x.test.ts:5:17)
      at processImmediate (internal/timers.js:464:21)

  2) example
       async failure:
     AssertionError: Expected to be rejected with "[Error: baz]" but got "Error: bar"
Hint: error
      at Control.assert (/home/piotr/Documents/projects/l2beat/node_modules/earljs/dist/Control.js:14:23)
      at /home/piotr/Documents/projects/l2beat/node_modules/earljs/dist/validators/toBeRejected.js:38:21
      at Generator.throw (<anonymous>)
      at rejected (/home/piotr/Documents/projects/l2beat/node_modules/earljs/dist/validators/toBeRejected.js:6:65)
```

The output could be:
```

  1) example
       regular failure:

      AssertionError: 123 not equal to 456
Hint: value mismatch
      + expected - actual

      -123
      +456
      
      at Context.<anonymous> (test/x.test.ts:5:17)
      at processImmediate (internal/timers.js:464:21)

  2) example
       async failure:
     AssertionError: Expected to be rejected with "[Error: baz]" but got "Error: bar"
Hint: error
      at Context.<anonymous> (test/x.test.ts:12:19)
      at processImmediate (internal/timers.js:464:21)
```

This can be achieved by creating the error in the `Control` constructor and removing `node_modules/earljs` entries from the stack trace thereby preserving both the synchronous stack trace as well as removing internals.

### PR DESCRIPTION
**Pull request by sz-piotr**
Closes #163

### CODE REVIEW

**Review by krzkaczor — COMMENTED** [review]
I just added basic tests. 

What is not entirely clear to me is that it seems that this PR is not only ensuring that stack traces are clean but also it adds an optimization by reusing a single AssertionError instance to handle multiple errors. 

The consequences of doing are much harder to me to asses properly. For example: what about parallel modes in test runners? 🤔  @hasparus thoughts?

**Comment by sz-piotr** [comment]
I haven't thought of that. The current flow means that once Control throws we go back to user code so it will never throw again. Maybe this should be made explicit, by adding a check that enforces that it is never re-used.

**Comment by krzkaczor** [comment]
Can we just keep on creating new error instance every time? I guess it will require an explicit `init` method to fix stack traces.

**Comment by sz-piotr** [comment]
That would mess up the stack trace I think, because when we recreate, we're in a completely different place.

**Comment by hasparus** [comment]
> The consequences of doing are much harder to me to asses properly. For example: what about parallel modes in test runners? 🤔 @hasparus thoughts?

To be fair, I'm scared of reusing the error instance too. I'm not quite sure if it would break parallel mode in mocha, but it's still still a bit tricky.

**Review by hasparus — APPROVED** [review]
Sweet 👍

**Review by krzkaczor — APPROVED** [review]

**Pull request merged**
