### PR TITLE
Fix formatting error

### PR DESCRIPTION
**Pull request by sz-piotr**

### CODE REVIEW

**Review by hasparus — APPROVED** [review]

**Comment by krzkaczor** [comment]
@sz-piotr will you fix the CI here?

**Comment by hasparus** [comment]
@krzkaczor I'll fix the CI, we're swapping PRs with Piotr.

**Comment by krzkaczor** [comment]
K. Feel free to merge and publish. Just remember to add a changeset.

**Comment by hasparus** [comment]
> Just remember to add a changeset.

( ͡° ͜ʖ ͡°)

**Pull request merged**
