### PR TITLE
Discussion / draft about new built-in validators and matchers

### PR DESCRIPTION
**Pull request by hasparus**
I've been working on https://github.com/dethcrypto/earl/issues/146 and reading issues and I think I've found a potential improvement.

So, https://github.com/dethcrypto/earl/issues/147 states that all basic matchers should have corresponding validators.
https://github.com/dethcrypto/earl/issues/85#issuecomment-745543939 suggests the same thing.

I'd love to have some more validators and matchers built-in, because well... they're quite convenient for concise tests and due to Jest's popularity, Copilot keeps suggesting them to me :P

Problem is, matchers and validators are not related at all from codebase perspective.

As an example, I've added `toBeTruthy` and `toBeFalsy` validators.
To add one new validator, we have to modify 4 files, 3 if we forget about tests.

To add corresponding matchers, we'd have two write 2 classes (similar to [_validators/numbers.ts_](https://github.com/dethcrypto/earl/blob/d99dceee728c2788cadcb0a7c3bab2e017abf196/packages/earljs/src/validators/numbers.ts)), and then assign onto `expect` in [_expect.ts_](https://github.com/dethcrypto/earl/blob/2ed1a8dbb299d7cb3137ea493d861022a91d0d0f/packages/earljs/src/expect.ts). This adds another 2 files to edit plus tests.

**Could we rethink the internal API in some way, to allow deriving validators from matchers?** (or conversly, as it's currently easier to write a validator than a matcher IMHO). 

Disclaimer: I don't want to refactor the code to make it more DRY and pretty, but I think that the current implementation can lead to matchers and validators diverging, either by missing the corresponding equivalent, or what's worse, by differences in logic between a matcher and validator of the same name.

### CODE REVIEW

**Comment by krzkaczor** [comment]
Yes definitely! I think I suggested it even *somewhere*. Initially, matchers and validators were quite different but now I think each matcher should have a corresponding validator for convenience reasons. Furthermore, it should be possible to derive such a validator automatically from the matcher implementation. 

Of course, there still be a possibility to have only a validator without a corresponding matcher but the other way around it doesn't make sense IMO...

**Comment by hasparus** [comment]
I gave up on deriving validators from matchers, and I added `truthy`, `nullish`, `falsy` and `defined` manually. We can merge this branch to close https://github.com/dethcrypto/earl/issues/85, @krzkaczor.

**Review by krzkaczor — APPROVED** [review]

**Comment by jlipps** [comment]
Any chance of a publish soon? I'm keen to use `toBeDefined` ^_^

**Comment by krzkaczor** [comment]
Sorry @jlipps, will be released this week. We need to merge one more thing.

**Comment by jlipps** [comment]
👍  thanks

**Comment by krzkaczor** [comment]
@jlipps Released as https://github.com/dethcrypto/earl/releases/tag/earljs%400.2.0 🔥

**Comment by jlipps** [comment]
\o/

**Pull request merged**
